# Generated by Django 3.0.5 on 2020-04-20 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usersmovie',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('movieid', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('poster', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Usersmovies',
        ),
    ]
