# Generated by Django 3.0.5 on 2020-04-23 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0002_auto_20200420_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usersmovies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieid', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('poster', models.CharField(max_length=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Usersmovie',
        ),
    ]
