# Generated by Django 3.0.5 on 2020-07-23 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20200424_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersmovie',
            name='rate',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
