# Generated by Django 3.0.5 on 2020-07-23 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_usersmovie_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmovie',
            name='rate',
            field=models.CharField(max_length=100),
        ),
    ]
